name: Validate Extension

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Package extension
        run: npm exec --yes @vscode/vsce package --out 1c-element-${{ github.sha }}.vsix
